/**
 * Created by donglele on 2017/11/2.
 */
export default {
    // cn: {
    //     lang: '中文',
    //     home: '主页',
    //     forum: '社区',
    //     wallet: '钱包',
    //     myWallet: '我的钱包',
    //     analyzeMnemonic: '助记词解析',
    //     walletSign: '离线签名',
    //     walletBroadcast: '签名广播',
    //     corpMail: '企业邮箱',
    //     siteTitle: 'Achain 区块链浏览器',

    //     success: '成功',
    //     fail: '失败',
    //     contract: '合约',
    //     accountName: '账户名称',
    //     accountAddr: '账户地址',
    //     accountBalc: '账户余额',

    //     transacTotal: '交易总数',
    //     transacTotalACT: '交易总金额',
    //     accountTotal: '账户总数',
    //     contractTotal: '合约总数',
    //     transacInLaseHour: '最近一小时交易量',
    //     transacPeak: '交易峰值/每小时',

    //     block: '区块',
    //     moreBlock: '更多区块',
    //     blockHeight: '区块高度',
    //     generateTime: '生成时间',
    //     transacNum: '交易数量',
    //     transacAmount: '交易金额',
    //     blockAgent: '出块代理',
    //     blockSize: '区块大小',
    //     blockList: '区块列表',

    //     prevBlock: '前一个区块',
    //     nextBlock: '后一个区块',
    //     blockOverview: '区块信息概览',
    //     blockAward: '出块奖励',
    //     blockCommission: '手续费',
    //     blockTime: '出块时间',
    //     transacRec: '交易记录',

    //     transac: '交易',
    //     moreTransac: '更多交易',
    //     transfer: '转账',
    //     transacTypes: ['转账','代理领工资','注册账户','注册代理','升级代理','更新账户',,,,,'注册合约','合约充值','合约升级','合约销毁','调用合约','合约出账'],
    //     transacInitiator: '发起方',
    //     transacType: '交易类型',
    //     confirmTime: '确认时间',
    //     // contractFunc: '合约调动函数名',
    //     transacRecipient: '接收方',
    //     transacNote: '备注',
    //     contractParam: '合约调用的参数',
    //     transacResult: '交易结果',

    //     contractTitle: '合约',
    //     contractAddr: '合约地址',
    //     contractOverview: '合约概览',
    //     contractName: '合约名称',
    //     contractStatus: '合约状态',
    //     contractStatusList: ['销毁','临时','永久'],
    //     contractBalance: '合约余额',
    //     registTime: '注册时间',
    //     contractOwner: '合约所有者',
    //     contractHash: '合约字节码Hash',
    //     contractDesc: '合约描述',
    //     contractType: '合约类型',
    //     contractTypes: ['普通','COIN'],
    //     contractFunc: '函数',
    //     contractEvent: '事件',
    //     eventType: '事件类型',
    //     eventParams: '事件参数',
    //     addressTip: '余额为0的币种不显示',

    //     extTrade: '扩展交易',


    //     noData: '暂无数据',
    //     transacUnit: '笔',
    //     btnContext: '展开 | 收起',
    //     lastBlockTip: '已经是最后一个区块了~',
    //     firstBlockTip: '没有更早的区块了~',
    //     networkErr: '网络异常，请稍后再试',
    //     serverErr: '服务器异常，请稍后再试',
    //     typeSearch: '请输入搜索内容'
    // },


    en: {
        lang: 'English',
        home: 'HOME',
        // forum: 'Forum',
        // wallet: 'Wallet',
        // myWallet: 'My Wallet',
        // analyzeMnemonic: 'Analyze Mnemonic',
        // walletSign: 'Signature',
        // walletBroadcast: 'Broadcast',
        // corpMail: 'Enterprise Mailbox',
        blockchain: 'BLOCKCHAIN',
        blockList: 'View Blocks',
        dealList: 'View Txns',
        siteTitleSsc: 'SSC Block Chain Browser',
        siteTitleAchain: 'Achain Block Chain Browser',
        success: 'Success',
        fail: 'Fail',
        sscBalance:'SSC Balance',
        jrBlance:'JR10 Balance',

        contract: 'Contract | Contracts',
        accountName: 'Account Name',
        accountAddr: 'Account Address',
        accountBalc: 'Balance',
        transac: 'Transaction | Transactions',
        ranking: 'Top Accounts',
        blockRanking: 'Ranking',
        blockCoin: 'Coin',
        blockAddress:'Address',
        blockAmount:'Amount',
        // transacTotal: 'Number of Transactions',
        // transacTotalACT: 'Amount of Transactions',
        // accountTotal: 'Number of Accounts',
        // contractTotal: 'Number of Contracts',
        // transacInLaseHour: 'Trading Volume in Last Hour',
        // transacPeak: 'Transaction Peak/ Per Hour',
        coinType: 'Coin type',
        block: 'Block | Blocks',
        moreBlock: 'View All',
        blockHeight: 'Block Height',
        generateTime: 'Generation Time',
        transacNum: 'Number of Transactions',
        transacAmount: 'Amount of Transactions',
        dealTxHash: 'TxHash',
        dealtime: 'Time',
        dealFrom: 'From',
        dealTo: 'To',
        dealValue: 'Value',

        blockAgent: 'Block Issuance Agent',
        blockSize: 'Block Size',
        // blockList: 'Block List',
        agentOwner: "mined by",
        prevBlock: 'Prev Block',
        nextBlock: 'Next Block',
        blockOverview: 'Block Information Overview',
        blockAward: 'Block Issuance Awards',
        blockCommission: 'Commission Charge',
        blockTime: 'Block Issuance Time',
        transacRec: 'Transaction Record',


        moreTransac: 'View All',
        transfer: 'transfer',
        transacTypes: ['Transfer','Agent Gets Paid','Account Registration','Registration Agent','Upgrade Agent','Update Account',,,,,'Contract Registration','Contract Recharge','Contract Upgrade','Contract Destruction','Contract Calling','Transfer From Contract'],
        transacInitiator: 'Initiator',
        transacType: 'Type of Transaction',
        confirmTime: 'Confirmation Time',
        // contractFunc: 'Parameters Called by Contract',
        transacRecipient: 'Recipient',
        transacNote: 'Notes',
        contractParam: 'Parameters Called by Contract',
        transacResult: 'Result of Transactions',

        contractTitle: 'Contract',
        contractAddr: 'Contract Address',
        contractOverview: 'Contract Overview',
        contractName: 'Contract Name',
        contractStatus: 'Contract Status',
        contractStatusList: ['Destroyed','Temporary','Permanent'],
        contractBalance: 'Contract Balance',
        registTime: 'Registration Time',
        contractOwner: 'Contract Owner',
        contractHash: 'Contract Bytecode Hash',
        contractDesc: 'Contract Description',
        contractType: 'Contract Type',
        contractTypes: ['Common','COIN'],
        contractFunc: 'Function',
        contractEvent: 'Event',
        eventType: 'Event Type',
        eventParams: 'Event Parameters',
        addressTip: 'Currencies with empty balance are not displayed',

        extTrade: 'Extended Transactions',


        noData: 'No Result',
        transacUnit: '',
        btnContext: 'Expand | Collapse',
        lastBlockTip: "It's been the last one~",
        firstBlockTip: 'No more previous block~',
        networkErr: 'Network exception, please try again later',
        serverErr: 'Server exception, please try again later',
        typeSearch: 'Please Type Your Search',
        
        
        //多链浏览器
        achain:'Achain浏览器',
        selfsell: 'SelfSell浏览器',

    }
}
