/**
 * Created by donglele on 2017/11/2.
 */
export default {
    cn: {
        lang: '中文',
        home: '主页',
        forum: '社区',
        wallet: '钱包',
        myWallet: '我的钱包',
        analyzeMnemonic: '助记词解析',
        walletSign: '离线签名',
        walletBroadcast: '签名广播',
        corpMail: '企业邮箱',
        siteTitle: 'Achain 区块链浏览器',

        success: '成功',
        fail: '失败',
        contract: '合约',
        accountName: '账户名称',
        accountAddr: '账户地址',

        block: '区块',
        moreBlock: '更多区块',
        blockHeight: '区块高度',
        generateTime: '生成时间',
        transacNum: '交易数量',
        transacAmount: '交易金额',
        blockAgent: '出块代理',
        blockSize: '区块大小',
        blockList: '区块列表',

        prevBlock: '前一个区块',
        nextBlock: '后一个区块',
        blockOverview: '区块信息概览',
        blockAward: '出块奖励',
        blockCommission: '手续费',
        blockTime: '出块时间',
        transacRec: '交易记录',

        transac: '交易',
        moreTransac: '更多交易',
        transfer: '转账',
        transacTypes: ['转账','代理领工资','注册账户','注册代理','升级代理','更新账户',,,,,'注册合约','合约充值','合约升级','合约销毁','调用合约','合约出账'],
        transacInitiator: '发起方',
        transacType: '交易类型',
        confirmTime: '确认时间',
        // contractFunc: '合约调动函数名',
        transacRecipient: '接收方',
        transacNote: '备注',
        contractParam: '合约调用的参数',
        transacResult: '交易结果',

        contractTitle: '合约',
        contractAddr: '合约地址',
        contractOverview: '合约概览',
        contractName: '合约名称',
        contractStatus: '合约状态',
        contractStatusList: ['销毁','临时','永久'],
        contractBalance: '合约余额',
        registTime: '注册时间',
        contractOwner: '合约所有者',
        contractHash: '合约字节码Hash',
        contractDesc: '合约描述',
        contractType: '合约类型',
        contractTypes: ['普通','COIN'],
        contractFunc: '函数',
        contractEvent: '事件',
        issueTotalAmount: '发行总量',
        officialLink: '官方链接',
        placehold: '合约名称、合约关键字、合约ID',
        contractTip: '只显示永久状态的正式合约',

        noData: '暂无数据',
        transacUnit: '笔',
        lastBlockTip: '已经是最后一个区块了~',
        firstBlockTip: '没有更早的区块了~',
        networkErr: '网络异常，请稍后再试',
        serverErr: '服务器异常，请稍后再试',
        typeSearch: '请输入搜索内容',

        broadcastResult: '广播结果',
        broadcastFail: '广播失败',
        broadcastSuccess: '广播成功',
        broadcastProcessing: '广播中...',
        broadcastWrongCode: '图形验证码错误',
        fillMessage: '请填写您的签名信息',
        noImageCode: '请填写图形验证码'
    },


    en: {
        lang: 'English',
        home: 'Home',
        forum: 'Forum',
        wallet: 'Wallet',
        myWallet: 'My Wallet',
        analyzeMnemonic: 'Analyze Mnemonic',
        walletSign: 'Signature',
        walletBroadcast: 'Broadcast',
        corpMail: 'Enterprise Mailbox',
        siteTitle: 'Achain Block Chain Browser',

        success: 'Success',
        fail: 'Fail',
        contract: 'Contract | Contracts',
        accountName: 'Account Name',
        accountAddr: 'Account Address',

        block: 'Block | Blocks',
        moreBlock: 'View More',
        blockHeight: 'Block Height',
        generateTime: 'Generation Time',
        transacNum: 'Number of Transactions',
        transacAmount: 'Amount of Transactions',
        blockAgent: 'Block Issuance Agent',
        blockSize: 'Block Size',
        blockList: 'Block List',

        prevBlock: 'Prev Block',
        nextBlock: 'Next Block',
        blockOverview: 'Block Information Overview',
        blockAward: 'Block Issuance Awards',
        blockCommission: 'Commission Charge',
        blockTime: 'Block Issuance Time',
        transacRec: 'Transaction Record',

        transac: 'Transaction | Transactions',
        moreTransac: 'View More',
        transfer: 'transfer',
        transacTypes: ['Transfer','Agent Gets Paid','Account Registration','Registration Agent','Upgrade Agent','Update Account',,,,,'Contract Registration','Contract Recharge','Contract Upgrade','Contract Destruction','Contract Calling','Transfer From Contract'],
        transacInitiator: 'Initiator',
        transacType: 'Type of Transaction',
        confirmTime: 'Confirmation Time',
        // contractFunc: 'Parameters Called by Contract',
        transacRecipient: 'Recipient',
        transacNote: 'Notes',
        contractParam: 'Parameters Called by Contract',
        transacResult: 'Result of Transactions',

        contractTitle: 'Contract',
        contractAddr: 'Contract Address',
        contractOverview: 'Contract Overview',
        contractName: 'Name',
        contractStatus: 'Status',
        contractStatusList: ['Destroyed','Temporary','Permanent'],
        contractBalance: 'Contract Balance',
        registTime: 'Registration Time',
        contractOwner: 'Contract Owner',
        contractHash: 'Contract Bytecode Hash',
        contractDesc: 'Contract Description',
        contractType: 'Type',
        contractTypes: ['COMMON','COIN'],
        contractFunc: 'Function',
        contractEvent: 'Event',
        issueTotalAmount: 'Total Supply',
        officialLink: 'Official Links',
        placehold: 'Name、Keyword、ID',
        contractTip: 'Only formal contracts with the permanent state are displayed.',

        noData: 'No Result',
        transacUnit: '',
        lastBlockTip: "It's been the last one~",
        firstBlockTip: 'No more previous block~',
        networkErr: 'Network exception, please try again later',
        serverErr: 'Server exception, please try again later',
        typeSearch: 'Please Type Your Search',

        broadcastResult: 'Result',
        broadcastSuccess: 'Success to broadcast',
        broadcastProcessing: 'In the process',
        broadcastFail: 'Fail to broadcast',
        broadcastWrongCode: 'Invalid image code',
        fillMessage: 'Please enter your signature message',
        noImageCode: 'Please enter the image code'
    }
}
