/**
 * Created by donglele on 2017/11/2.
 */
export default {
    cn: {
        lang: '中文',
        home: '主页',
        forum: '社区',
        wallet: '钱包',
        myWallet: '我的钱包',
        analyzeMnemonic: '助记词解析',
        walletSign: '离线签名',
        walletBroadcast: '签名广播',
        corpMail: '企业邮箱',
        siteTitle: 'Achain 区块链浏览器',

        success: '成功',
        fail: '失败',
        contract: '合约',
        accountName: '账户名称',
        accountAddr: '账户地址',

        broadcast: '广播',
        goBroadcast: '去广播',
        optional: ' (可选)',

        contractTransfer: '转账离线签名',
        contractCall: '合约调用签名',

        label1: '私钥或助记词',
        label2: '转账类型',
        label3: '转账地址',
        label4: '转账数量',
        label5: '转帐备注',

        label6: '合约ID',
        label7: '调用方法',
        label8: '参数',

        noAddress: '地址不能为空',
        noPrivkey: '请输入私钥',
        noContractId: '合约ID不能为空',
        noContractFn: '调用方法不能为空',
        noContractParams: '调用参数不能为空',
        noTransferAddress: '转账地址不能为空',
        noTransferAmount: '转账金额不能为空',
        noMnemonic: '请输入助记词',
        noPassword: '请输入密码',
        wrongTransferNote: '转账备注不能超过40个字节',
        wrongTransferAmount: '转账金额错误',
        wrongPrivkey: '私钥格式错误',
        wrongContractId: '合约ID格式错误',
        wrongACTaddress: '地址格式错误',
        wrongFiletype: '文件格式错误',

        generateSign: '生成签名',
        viewTrans: '查看交易',

        walletTitle: '创建离线钱包',
        walletLink: '已有钱包地址?',
        inputPhrase: '填写助记词',
        phrase: '记下助记词',
        verifyPhrase: '验证助记词',
        toVerify: '已记下助记词，去验证',
        toWallet: '进入钱包',
        setPwd: '设置密码',
        password: '密码',
        comfirmPwd: '确认密码',
        passwordTip: '密码两次输入不一致，请您再次确认',
        phraseConfirm: '我已经记住了助记词',
        walletTip: '助记词用于创建钱包地址，拥有助记词和密码即可完全控制钱包资产，Achain浏览器不会存储任何有关助记词，及其密码相关的数据，请务必妥善保存。',
        next: '下一步',
        toSign: '去签名',
        address: '地址',
        generateAddr: '生成地址',
        generatePrivKey: '生成私钥',
        usePhrase: '使用助记词生成私钥',
        phraseErrorTip: '助记词错误',

        myAddress: '我的ACT地址:',
        balance: '余额',
        myCode: '我的收款码',
        changeAddress: '更改ACT地址',
        importAddress: '立即导入ACT地址',

        contractTitle: '合约',
        privKey: '私钥',
        mnemonic: '助记词',
        wifPrivKey: 'WIF私钥',
        importPriv: '导入私钥',
        importGkey: '导入gkey文件',
        importMnemonic: '导入助记词',
        nofile: '请选择文件',
        confirm: '确定',

        noData: '暂无数据',
        transacUnit: '笔',
        lastBlockTip: '已经是最后一个区块了~',
        firstBlockTip: '没有更早的区块了~',
        networkErr: '网络异常，请稍后再试',
        serverErr: '服务器异常，请稍后再试',
        typeSearch: '请输入搜索内容',

        broadcastResult: '广播结果',
        broadcastFail: '广播失败',
        broadcastSuccess: '广播成功',
        broadcastProcessing: '广播中...',
        broadcastWrongCode: '图形验证码错误',
        fillMessage: '请填写您的签名信息',
        errMessage: '非法签名信息',
        noImageCode: '请填写图形验证码'
    },


    en: {
        lang: 'English',
        home: 'Home',
        forum: 'Forum',
        wallet: 'Wallet',
        myWallet: 'My Wallet',
        analyzeMnemonic: 'Analyze Mnemonic',
        walletSign: 'Signature',
        walletBroadcast: 'Broadcast',
        corpMail: 'Enterprise Mailbox',
        siteTitle: 'Achain Block Chain Browser',

        success: 'Success',
        fail: 'Fail',
        contract: 'Contract | Contracts',
        accountName: 'Account Name',
        accountAddr: 'Account Address',

        broadcast: 'Broadcast',
        goBroadcast: 'Broadcast it',
        optional: ' (optional)',

        contractTransfer: 'Transfer',
        contractCall: 'Contract Calling',

        label1: 'Private key or Mnemonic',
        label2: 'Type',
        label3: 'Address',
        label4: 'Amount',
        label5: 'Note',

        label6: 'Contract ID',
        label7: 'Function',
        label8: 'Parameters',

        generateSign: 'Generate',
        viewTrans: 'View transaction',

        walletTitle: 'Create Wallet Now',
        walletLink: 'Already have wallet address',
        inputPhrase: 'input mnemonic',
        phrase: 'Mnemonic',
        verifyPhrase: 'Verify Mnemonic',
        toVerify: 'I already remember the mnemonic',
        toWallet: 'Enter Wallet',
        setPwd: 'Set Password',
        password: 'Password',
        comfirmPwd: 'Confirm Password',
        passwordTip: 'The passwords input twice are inconsistent, please confirm again',
        phraseConfirm: 'I already remember the mnemonic',
        walletTip: 'Mnemonic helps you to create your wallet address. Please have attention that anyone with your mnemonic and password can have full control on your Cryptocurrency. Achain browser never store your mnemonic, password and any relative data. Please keep your mnemonic and password in safe place.',
        next: 'next',
        toSign: ' Sign',
        address: 'Address',
        generateAddr: 'Generate address',
        generatePrivKey: 'Generate key',
        usePhrase: 'Use mnemonic to generate',
        phraseErrorTip: 'Mnemonic error',

        contractTitle: 'Contract',
        privKey: 'Private Key',
        mnemonic: 'Mnemonic',
        wifPrivKey: 'WIF Private Key',
        importGkey: 'Import .gkey',
        importPriv: 'Import private key',
        importMnemonic: 'Import mnemonic',
        nofile: 'Please select a file',
        confirm: 'Confirm',

        myAddress: 'My ACT Address:',
        balance: 'Balance',
        myCode: 'My QRcode',
        changeAddress: 'Change ACT Address',
        importAddress: 'Import ACT Address',

        noAddress: 'Address is required',
        noPrivkey: 'Please enter private key',
        noContractId: 'Contract ID is required',
        noContractFn: 'Contract function is required',
        noContractParams: 'Contract parameter is required',
        noTransferAddress: 'Transfer address is required',
        noTransferAmount: 'Transfer amount is required',
        noMnemonic: 'Please enter mnemonic',
        noPassword: 'Please enter password',
        wrongTransferNote: 'Transfer note should not exceed 40 bytes',
        wrongTransferAmount: 'Invalid transfer amount',
        wrongPrivkey: 'Invalid private key',
        wrongContractId: 'Invalid contract ID',
        wrongACTaddress: 'Invalid address',
        wrongFiletype: 'Invalid file type',

        noData: 'No Result',
        transacUnit: '',
        lastBlockTip: "It's been the last one~",
        firstBlockTip: 'No more previous block~',
        networkErr: 'Network exception, please try again later',
        serverErr: 'Server exception, please try again later',
        typeSearch: 'Please Type Your Search',

        broadcastResult: 'Result',
        broadcastSuccess: 'Success to broadcast',
        broadcastProcessing: 'In the process',
        broadcastFail: 'Fail to broadcast',
        broadcastWrongCode: 'Invalid image code',
        fillMessage: 'Please enter your signature message',
        errMessage: 'Invalid signature message',
        noImageCode: 'Please enter the image code'
    }
}
